#!/usr/bin/env python3
"""Assemble an ETCa program and emit it as a Spade boot ROM.

    program.s --etc-as--> raw binary --this script--> src/program.spade

Each ETCa instruction is 2 bytes with the format-marker byte first, so bytes
are packed big-endian into uint<16> words (word = byte0<<8 | byte1) and written
as a combinational lookup:

    pub fn get_rom_op(addr: uint<16>) -> uint<16> {
        let program: [uint<16>; N] = [w0, w1, ...];
        if addr < N { program[trunc(addr)] } else { <NoOp> }
    }

This replaces the hardcoded bootloader() in the CPU's fetch region logic; call
it with the ROM-relative offset. It synthesises to a LUT mux (not BRAM), so
keep the program small, that's fine for a boot stub whose eventual job is just
to copy the real program from SPI flash into RAM and jump to it.

Usage:
    tools/asm2spade.py programs/count.s
    tools/asm2spade.py programs/count.s --out src/program.spade
    tools/asm2spade.py --bin some.bin            # skip assembling
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile

DEFAULT_AS = os.path.expanduser("~/Projects/etca-asm/.venv/bin/etc-as")


def assemble(src: str, asm: str) -> bytes:
    with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as tmp:
        out = tmp.name
    try:
        subprocess.run(
            [asm, "-mnaked-reg", "-mformat=binary", src, "-o", out],
            check=True,
        )
        with open(out, "rb") as f:
            return f.read()
    finally:
        os.unlink(out)


def pack_words(data: bytes) -> list[int]:
    if len(data) % 2 != 0:
        sys.exit(f"error: {len(data)} bytes is not a whole number of 16-bit words")
    return [(data[i] << 8) | data[i + 1] for i in range(0, len(data), 2)]


def emit_spade(words: list[int]) -> str:
    n = len(words)
    body = ", ".join(f"0x{w:04x}" for w in words)
    return (
        "// GENERATED by tools/asm2spade.py. Do not edit by hand.\n"
        f"// {n}-word boot ROM.\n\n"
        "pub fn get_rom_op(addr: uint<16>) -> uint<16> {\n"
        f"    let program: [uint<16>; {n}] = [{body}];\n\n"
        f"    if addr < {n} {{\n"
        "        program[trunc(addr)]\n"
        "    } else {\n"
        "        0b00_01_1001_000_000_00\n"
        "    }\n"
        "}\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description="ETCa asm -> Spade init array")
    ap.add_argument("src", nargs="?", help="assembly source (.s)")
    ap.add_argument("--bin", help="use an already-assembled binary instead of src")
    ap.add_argument("--out", default="src/program.spade", help="output Spade file")
    ap.add_argument("--as", dest="asm", default=DEFAULT_AS, help="path to etc-as")
    args = ap.parse_args()

    if args.bin:
        with open(args.bin, "rb") as f:
            data = f.read()
    elif args.src:
        data = assemble(args.src, args.asm)
    else:
        ap.error("give an assembly source or --bin")

    words = pack_words(data)
    with open(args.out, "w") as f:
        f.write(emit_spade(words))
    print(f"wrote {args.out}: {len(words)} words")


if __name__ == "__main__":
    main()
